version = "** LambdaMOO Database, Format Version {version:d} **"
var_count = "{count:d} variables"
clock_count = "{count:d} clocks"
task_count = "{count:d} queued tasks"
task_header = "{:d} {firstLineno:d} {id:d} {st:d}"
activation_header = "{this:d} {:d} {:d} {player:d} {:d} {programmer:d} {vloc:d} {:d} {debug:d}"
pending_values_count = "{count:d} values pending finalization"
suspended_task_count = "{count:d} suspended tasks"
suspended_task_header = "{startTime:d} {id:d}{endchar} {value:d}"
interrupted_task_count = "{count:d} interrupted tasks"
vm_header = "{top:d} {vector:d} {funcId:d} {maxStackframes:d}"

langver = "language version {version:d}"
stack_header = "{slots:d} rt_stack slots in use"
pc = "{pc:d} {bi_func:d} {error:d}"
waif_header = "{flag:l} {index:d}"
